### ISSUE TITLE
epubs still corrupted

### ISSUE THREAD

**Issue by yacc143** [juruen/rmapi#12] opened 2018-03-26 13:34 UTC
Hi!

Even after the current change the rM complains about corrupted files, sigh.

I've compared the current upload and the official client upload, by downloading it back, and found the following differences:

* different uuid
* epub is binary equal (actually same md5sum) for both clients, but different from the original epub uploaded.
* the content file is pretty printed for the official client, and it has a transform key: 

`"transform": {
        "m11": 1,
        "m12": 0,
        "m13": 0,
        "m21": 0,
        "m22": 1,
        "m23": 0,
        "m31": 0,
        "m32": 0,
        "m33": 1
    }
`
* pagedata is the same again (md5sum)
* the official client zip file contains a uuid.thumbnails folder with 20 page thumbnails.

[57f16dca-8746-426b-9a06-b3a5d14e1e66.zip](https://github.com/juruen/rmapi/files/1848000/57f16dca-8746-426b-9a06-b3a5d14e1e66.zip)
[Bonesetter - Laurence Dahners.zip](https://github.com/juruen/rmapi/files/1848001/Bonesetter.-.Laurence.Dahners.zip)

**Comment by juruen** [comment] 2018-03-26 14:21
This is interesting.

I've tried with some epubs from [gutenberg](http://www.gutenberg.org/) such as [this one](http://www.gutenberg.org/ebooks/56830.epub.images?session_id=37814bb8c334506982e7d87d0784605503bbb743) and it works fine.

We need to figure out why it doesn't work with the one you are trying to upload.

**Comment by yacc143** [comment] 2018-03-26 15:01
Well, some observation: Uploading exactly the same epub via the official client DOES work, for whatever reason. Another: My epubs are all produced by calibre.

Sadly my Go knowledge is non-existant, so I cannot play and debug the issue myself. :-1:

**Comment by yacc143** [comment] 2018-03-26 15:05
Another observation:

While the epub file (which is technically only a zip anyways) seems to be changed during the upload, it's content does not change at all.

So my guess would be that the rM opens and rewrites the zip file, potentially with slightly different settings, during it's import.

**Comment by yacc143** [comment] 2018-03-26 15:09
And yes, the Gutenberg book you've linked to works with rM too, at least the behavior is deterministic, if baffling.

**Comment by juruen** [comment] 2018-03-26 15:37
When I have some time, I'll go back to check what the desktop client does using `mitmproxy`. That should help us understand what's going on here.

**Comment by klardotsh** [comment] 2019-01-21 22:09
Chiming in mostly as a +1 with context: my ePubs are all Calibre exports (sadly I can't share them here as test files) which push fine with the USB HTTP interface, and end up corrupted when trying to push with `rmapi`.

If there's anything in particular I can do to help debug this, I'd be happy to do so! I'm thinking I might poke at the web inspector console when pushing a file through that (at least so-far working) interface to see if there's anything interesting.

**Comment by klardotsh** [comment] 2019-01-26 00:15
Here's a HAR file of what happens when I upload an ePub through the `10.11.99.1` web UI drag-and-drop - hope it helps.

The ePub document is https://github.com/mattharrison/Tiny-Python-3.6-Notebook as converted with `pandoc --from rst --to epub python.rst -o python.epub --metadata title="Tiny Python 3.6 Notebook"` (pretty sure this is fine to post in this format, as converting document formats isn't a derivative per CC licensing)

https://github.com/klardotsh/lfs-filedump/raw/master/Archive%2019-01-25%2016-05-45.har

**Comment by klardotsh** [comment] 2019-01-26 00:48
Possibly way more interesting are these two JSON entries (available in the HAR because I didn't really scrub it - whatever) of two uploads of Michelle Obama's "Becoming" I have on my device.

The former was uploaded with the web UI with drag-and-drop, and can be read successfully. The latter was uploaded with `rmapi`, and is (as far as the device is concerned), a corrupted file.

```json
 {
"Bookmarked": false,
"CurrentPage": 0,
"ID": "dcf434c0-1b7f-46aa-8e74-f0607c8ac4bc",
"ModifiedClient": "2019-01-25T23:59:10.121121Z",
"Parent": "",
"Type": "DocumentType",
"Version": 1,
"VissibleName": "Becoming - Michelle Obama.epub",
"extraMetadata": {
},
"fileType": "epub",
"fontName": "",
"lastOpenedPage": 0,
"lineHeight": -1,
"margins": 100,
"orientation": "portrait",
"pageCount": 657,
"textScale": 1,
"transform": {
"m11": 1,
"m12": 0,
"m13": 0,
"m21": 0,
"m22": 1,
"m23": 0,
"m31": 0,
"m32": 0,
"m33": 1
}
},
{
"Bookmarked": false,
"CurrentPage": 0,
"ID": "ea038c32-6d13-4710-8742-a85003f30e09",
"ModifiedClient": "2019-01-25T23:40:52.00Z",
"Parent": "",
"Type": "DocumentType",
"Version": 1,
"VissibleName": "Becoming - Michelle Obama",
"extraMetadata": {
},
"fileType": "",
"fontName": "",
"lastOpenedPage": 0,
"lineHeight": -1,
"margins": 100,
"orientation": "portrait",
"pageCount": 1,
"textScale": 1,
"transform": {
"m11": 1,
"m12": 0,
"m13": 0,
"m21": 0,
"m22": 1,
"m23": 0,
"m31": 0,
"m32": 0,
"m33": 1
}
},
```

**Comment by juruen** [comment] 2019-01-26 04:04
I'll try to have a look this weekend again.

**Comment by juruen** [comment] 2019-02-02 17:06
I had sometime to investigate this but I haven't managed to find the root cause.

I'm not giving up though!

**Comment by ddvk** [comment] 2020-04-23 11:11
what is the status of this one? i could not reproduce it with the attached files

**Comment by ddvk** [comment] 2020-09-22 09:18
no new info, closing this one

**Closed by ddvk** 2020-09-22 09:18 UTC
Labels: bug
