### ISSUE TITLE
Failed to fetch documents 401 Unauthorized Error

### ISSUE THREAD

**Issue by ejurga** [juruen/rmapi#180] opened 2021-05-26 21:35 UTC
rmapi gives the following error on all commands: 

ERROR: 2021/05/26 17:28:27 api.go:34: failed to fetch documents 401 Unauthorized Error
ERROR: 2021/05/26 17:28:27 main.go:30: retrying...
ERROR: 2021/05/26 17:28:27 main.go:35: failed to build documents tree

Even after updating to the latest version, and after refreshing my authentication token. The program worked flawlessly until today, and I think I last used it 2 weeks ago with no problem. Did something change with the ReMarkble API?

**Comment by bitterjug** [comment] 2021-05-27 05:54
I have experienced a similar failure today. This is all I got:
```
ERROR: 2021/05/27 06:48:57 main.go:42: failed to build documents tree, last error: failed to fetch document tree 401 Unauthorized Error
```

**Comment by ddvk** [comment] 2021-05-27 08:17
duplicate of #177

**Closed by ddvk** 2021-05-27 08:17 UTC
