### ISSUE TITLE
Watermark on exported PDF

### ISSUE THREAD

**Issue by ademasi** [juruen/rmapi#118] opened 2020-07-28 09:58 UTC
I installed rmapi with go directly from the master branch.

Every time I am using the **geta** command, I get this message:

`Unlicensed copy of unidoc
To get rid of the watermark - Please get a license on https://unidoc.io
`
And the PDF contains the watermark.

 I saw a [commit](https://github.com/juruen/rmapi/tree/7ac78e3b334ce11d8ce18455da4716739ad72b5b) from @ddvk  integrating the license, hence I don't understand why I get the watermark.

**Comment by ddvk** [comment] 2020-07-28 10:04
what were the steps?
doing a clean build e.g:
```
git clone ....
go build
./rmapi geta zzzz
```
with go1.14.4  linux/amd64 I cannot replicate it.

**Comment by ademasi** [comment] 2020-07-28 10:09
I installed it with `go get -u github.com/juruen/rmapi`. 

I just tried with a clean build,  cloning with git and it works well.
I am not really familiar with go build system, I though that **go gets** would  do the same action as git clone & go build.
Thanks for your fast reply.

**Comment by ddvk** [comment] 2020-07-28 10:47
i managed to replicate the way you did.
btw, what go version are you using?
this is surprising, it seems that doing go get compiles in a way that breaks the shadowing of the license variable with go:linkname, either a go bug or I lack the knowledge.

we can either change the readme or look further for the root cause.

**Comment by ademasi** [comment] 2020-07-28 11:24
`alex@daedalus ~> go version
go version go1.14.6 linux/amd64
`
Go was installed with pacman on Arch.

**Comment by OpoOpo** [comment] 2020-07-30 07:43
I have the same problem

**Comment by juruen** [comment] 2020-07-30 09:14
This is interesting!

I can repro the issue on OSX with go 1.13 and 1.14.

However, if I run:

```bash
go get  -u -d  github.com/juruen/rmapi && (cd $GOPATH/src/github.com/juruen/rmapi  && go install)
```
it works fine.

The pre-built binaries that are available on the repo also work fine on OSX.

So there's something hapenning in the `go get -u` process that breaks it.

**Comment by juruen** [comment] 2020-07-30 10:40
@ddvk I'm wondering if it could be an order issue where the module init function is not being called in the right order?

**Comment by ddvk** [comment] 2020-07-30 13:20
i played a bit, but havent figured it out. the variable does not get linked (it is nil) as if the go:linkname is ignored or the packagename is wrong. the order should be correct as this package is imported

**Comment by ddvk** [comment] 2020-07-30 21:30
Found a workaround:
```
GO111MODULE=on go get github.com/juruen/rmapi@latest
```
My theory: It seems that the problem is a usage of go modules + linkname magic.
using `go get` uses `GOAPTH` which in this cases silently uses `unipdf/common/license` instead of `unipdf/v3/common/license`

**Comment by ddvk** [comment] 2020-07-31 19:50
closing the issue, as resolved

**Closed by ddvk** 2020-07-31 19:50 UTC
