### ISSUE TITLE
linux version of 0.0.4 -- prebuilt or instructions on how to build

### ISSUE THREAD

**Issue by curiouslarry** [juruen/rmapi#55] opened 2019-04-09 16:25 UTC

**Comment by curiouslarry** [comment] 2019-04-09 16:27
How does one build rmapi-0.0.4 on linux using "go"?   The only prebuilt release is version 0.0.2 and that does not work for me (it uploads the file as an empty directory)

**Comment by dgoerger** [comment] 2019-04-10 22:09
I'm on OpenBSD, but the command should work the same on Linux. I use the following to compile a statically-linked binary:
```
go build -ldflags "-linkmode external -extldflags -static" -a github.com/juruen/rmapi
```
Static linking will result in a larger binary (16.5M vs ~9M on OpenBSD), but on Linux it means that a binary compiled on CentOS 64bit will also work on Ubuntu 64bit, despite those operating systems using different versions of glibc and other libraries. That makes it more portable.

If you don't need it statically-linked, this command will yield a smaller binary:
```
go build -a github.com/juruen/rmapi
```

I hope this helps! (while I'm here, thanks devs for this great project!)

**Comment by dgoerger** [comment] 2019-04-12 20:00
@curiouslarry I did some digging, and actually you probably don't want to statically link `rmapi` against Linux's glibc---glibc has lazy loading of network functions, and the resulting binary [isn't actually static](https://bugzilla.redhat.com/show_bug.cgi?id=111298), which could result in undefined behaviour and messy nonsense. Hmm. I take back my recommendation if you're using Linux. Sorry for the confusion.

However I was able to compile a static amd64 binary using Linux's [musl libc](https://www.musl-libc.org/intro.html)---musl libc is designed for static linking---and tested it against Linuxes as old as CentOS 6.10. If you trust a random person on the Internet to compile code without injecting malicious nonsense into the binary (I didn't, but you shouldn't trust my saying so), I've temporarily uploaded a [compiled copy of 0.0.4 to my SDF webspace](https://sdf.org/~dgoerger/rmapi-linux).

But for personal use, dynamic linking should be fine:
```
go get -u github.com/juruen/rmapi
go build -a github.com/juruen/rmapi
```

Procedure to compile a musl libc static binary:
```
$ # fetch source
$ go get -u github.com/juruen/rmapi
$ # link against musl libc instead of glibc
$ export CC=/usr/bin/musl-gcc
$ # compile
$ go build -ldflags "-linkmode external -extldflags -static" -a github.com/juruen/rmapi
$ # confirm the binary is statically-linked (i.e. no dynamic links)
$ readelf -d ./rmapi
There is no dynamic section in this file.
```

**Comment by curiouslarry** [comment] 2019-04-22 22:04
Thanks for the help and was able to build.   However, whenever I do a "put xx.pdf"  it creates a directory rather than a single pdf file.   When I do this from my mac osx, everything works fine.   Any help would be appreciated.

**Comment by dgoerger** [comment] 2019-04-26 20:42
I'm unable to reproduce this on Linux. What distro and version of Go are you using?

```
$ uname -a && go version
```

Does it still happen with [this version](https://sdf.org/~dgoerger/rmapi-linux)? That one works for me (compiled on CentOS 7, run from CentOS 6).

**Comment by juruen** [comment] 2019-08-11 09:36
Closing this as there's a new built package for Linux that has been just released.

**Closed by juruen** 2019-08-11 09:36 UTC
