### ISSUE TITLE
Upload .zip file to restore document

### ISSUE THREAD

**Issue by lk11235** [juruen/rmapi#88] opened 2020-01-29 18:02 UTC
Hi, upon downloading files (through 'get' or 'mget') one is able to locally save .zip files of documents from the reMarkable cloud. But, is there currently a way to upload these .zip files back to the cloud using rmapi to effectively "restore" these documents after the originals have been deleted from the cloud? 

Namely, I'd like to be able to upload (ideally through 'mput') folders of documents that I've backed up from my reMarkable, and which exist on my local drive as a directory of .zip files, but have since been deleted on my tablet. This feature would be particularly useful when revisiting old research projects, for example.

**Comment by lk11235** [comment] 2020-01-29 18:05
Apologies, I've just now seen Issue #53 regarding this same suggestion. Have there been any updates on this endeavor?

**Comment by ddvk** [comment] 2020-04-24 09:35
closing as duplicate of #53

**Closed by ddvk** 2020-04-24 09:35 UTC
